#!/bin/bash

# ============================================================
# KHODAT VPS DOMAIN CONFIGURATION SCRIPT
# ============================================================
# Script cấu hình Nginx reverse proxy cho các services Docker
# Yêu cầu: VPS đã cài Nginx và Certbot
# ============================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ============================================================
# CONFIGURATION - THAY ĐỔI CÁC GIÁ TRỊ NÀY THEO NHU CẦU
# ============================================================

# Domain chính
MAIN_DOMAIN="khodat.com"

# Sub-domains cho các services
FRONTEND_DOMAIN="khachhang.${MAIN_DOMAIN}"      # Next.js Frontend
API_DOMAIN="api.${MAIN_DOMAIN}"               # Laravel Backend API
ADMIN_DOMAIN="${MAIN_DOMAIN}"           # OpenCart Admin
PMA_DOMAIN="pma.${MAIN_DOMAIN}"               # phpMyAdmin (optional)

# Server local ports (từ docker-compose.yml)
FRONTEND_PORT=3015
API_PORT=8015
ADMIN_PORT=8088
PMA_PORT=8095

# Email cho SSL certificate
SSL_EMAIL="admin@${MAIN_DOMAIN}"

# Nginx config directory
NGINX_AVAILABLE="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"

# ============================================================
# FUNCTIONS
# ============================================================

check_root() {
    if [ "$EUID" -ne 0 ]; then
        print_error "Script cần chạy với quyền root. Sử dụng: sudo $0"
        exit 1
    fi
}

check_nginx() {
    if ! command -v nginx &> /dev/null; then
        print_error "Nginx chưa được cài đặt. Cài đặt với: apt install nginx"
        exit 1
    fi
    print_success "Nginx đã được cài đặt"
}

check_certbot() {
    if ! command -v certbot &> /dev/null; then
        print_warning "Certbot chưa được cài đặt. Cài đặt ngay..."
        apt update
        apt install -y certbot python3-certbot-nginx
    fi
    print_success "Certbot đã sẵn sàng"
}

backup_nginx_config() {
    local backup_dir="/etc/nginx/backup_$(date +%Y%m%d_%H%M%S)"
    mkdir -p "$backup_dir"
    cp -r /etc/nginx/sites-available/* "$backup_dir/" 2>/dev/null || true
    cp -r /etc/nginx/sites-enabled/* "$backup_dir/" 2>/dev/null || true
    print_info "Đã backup config Nginx tại: $backup_dir"
}

create_nginx_config() {
    local domain=$1
    local port=$2
    local config_name=$3
    local config_file="${NGINX_AVAILABLE}/${config_name}"

    print_info "Tạo config cho: $domain -> localhost:$port"

    cat > "$config_file" <<EOF
# ============================================================
# Nginx Configuration for ${domain}
# Generated by setup-domain.sh on $(date)
# ============================================================

# Rate limiting zone
limit_req_zone \$binary_remote_addr zone=${config_name}_limit:10m rate=10r/s;

upstream ${config_name}_upstream {
    server 127.0.0.1:${port};
    keepalive 32;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${domain};

    # Redirect to HTTPS (sẽ được Certbot xử lý)
    location / {
        return 301 https://\$server_name\$request_uri;
    }

    # ACME challenge for Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
}

# server {
#     listen 443 ssl http2;
#     listen [::]:443 ssl http2;
#     server_name ${domain};

#     # SSL Configuration (sẽ được Certbot cập nhật)
#     # ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
#     # ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
#     # include /etc/letsencrypt/options-ssl-nginx.conf;
#     # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

#     # Security Headers
#     add_header X-Frame-Options "SAMEORIGIN" always;
#     add_header X-Content-Type-Options "nosniff" always;
#     add_header X-XSS-Protection "1; mode=block" always;
#     add_header Referrer-Policy "strict-origin-when-cross-origin" always;

#     # Logging
#     access_log /var/log/nginx/${config_name}_access.log;
#     error_log /var/log/nginx/${config_name}_error.log;

#     # Gzip compression
#     gzip on;
#     gzip_vary on;
#     gzip_min_length 1024;
#     gzip_proxied any;
#     gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml application/rss+xml application/atom+xml image/svg+xml;

#     # Rate limiting
#     limit_req zone=${config_name}_limit burst=20 nodelay;

#     # Proxy settings
#     location / {
#         proxy_pass http://${config_name}_upstream;
#         proxy_http_version 1.1;
#         proxy_set_header Host \$host;
#         proxy_set_header X-Real-IP \$remote_addr;
#         proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto \$scheme;
#         proxy_set_header Upgrade \$http_upgrade;
#         proxy_set_header Connection "upgrade";

#         # Timeouts
#         proxy_connect_timeout 60s;
#         proxy_send_timeout 60s;
#         proxy_read_timeout 60s;

#         # Buffer settings
#         proxy_buffer_size 128k;
#         proxy_buffers 4 256k;
#         proxy_busy_buffers_size 256k;
#     }

#     # Static files caching (cho frontend)
#     location ~* \.(jpg|jpeg|png|gif|ico|css|js|pdf|txt|woff|woff2|ttf|svg|eot)$ {
#         proxy_pass http://${config_name}_upstream;
#         proxy_set_header Host \$host;
#         expires 30d;
#         add_header Cache-Control "public, immutable";
#     }

#     # Health check endpoint
#     location /health {
#         access_log off;
#         return 200 "OK";
#         add_header Content-Type text/plain;
#     }
# }
EOF

    print_success "Đã tạo config: $config_file"
}

create_api_nginx_config() {
    local config_file="${NGINX_AVAILABLE}/khodat-api"

    print_info "Tạo config đặc biệt cho API: $API_DOMAIN"

    cat > "$config_file" <<EOF
# ============================================================
# Nginx Configuration for API (${API_DOMAIN})
# Optimized for Laravel Backend
# ============================================================

limit_req_zone \$binary_remote_addr zone=api_limit:10m rate=30r/s;

upstream api_upstream {
    server 127.0.0.1:${API_PORT};
    keepalive 64;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${API_DOMAIN};

    location / {
        return 301 https://\$server_name\$request_uri;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
}

# server {
#     listen 443 ssl http2;
#     listen [::]:443 ssl http2;
#     server_name ${API_DOMAIN};

#     # SSL sẽ được Certbot cấu hình

#     # Security Headers
#     add_header X-Frame-Options "DENY" always;
#     add_header X-Content-Type-Options "nosniff" always;
#     add_header X-XSS-Protection "1; mode=block" always;
#     add_header Referrer-Policy "strict-origin-when-cross-origin" always;

#     # CORS Headers cho API
#     add_header Access-Control-Allow-Origin "https://${FRONTEND_DOMAIN}" always;
#     add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS" always;
#     add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-Requested-With, Accept, Origin" always;
#     add_header Access-Control-Allow-Credentials "true" always;

#     # Handle preflight requests
#     if (\$request_method = OPTIONS) {
#         return 204;
#     }

#     # Logging
#     access_log /var/log/nginx/api_access.log;
#     error_log /var/log/nginx/api_error.log;

#     # Gzip
#     gzip on;
#     gzip_vary on;
#     gzip_min_length 256;
#     gzip_proxied any;
#     gzip_types application/json application/javascript text/css text/plain text/xml application/xml;

#     # Rate limiting - cao hơn cho API
#     limit_req zone=api_limit burst=50 nodelay;

#     # Client body size (cho upload)
#     client_max_body_size 100M;

#     # API Proxy
#     location / {
#         proxy_pass http://api_upstream;
#         proxy_http_version 1.1;
#         proxy_set_header Host \$host;
#         proxy_set_header X-Real-IP \$remote_addr;
#         proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto \$scheme;

#         # Timeouts dài hơn cho API
#         proxy_connect_timeout 120s;
#         proxy_send_timeout 120s;
#         proxy_read_timeout 120s;

#         # Buffer settings
#         proxy_buffer_size 128k;
#         proxy_buffers 8 256k;
#         proxy_busy_buffers_size 512k;
#     }

#     # Sanctum/Auth endpoints - rate limit chặt hơn
#     location ~ ^/(api/login|api/register|api/password|oauth) {
#         limit_req zone=api_limit burst=5 nodelay;
        
#         proxy_pass http://api_upstream;
#         proxy_http_version 1.1;
#         proxy_set_header Host \$host;
#         proxy_set_header X-Real-IP \$remote_addr;
#         proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto \$scheme;
#     }

#     # Storage/uploads
#     location /storage {
#         proxy_pass http://api_upstream;
#         proxy_set_header Host \$host;
#         expires 7d;
#         add_header Cache-Control "public";
#     }

#     # Health check
#     location /health {
#         access_log off;
#         proxy_pass http://api_upstream;
#     }
# }
EOF

    print_success "Đã tạo API config: $config_file"
}

enable_site() {
    local config_name=$1
    local source="${NGINX_AVAILABLE}/${config_name}"
    local target="${NGINX_ENABLED}/${config_name}"

    if [ -L "$target" ]; then
        rm "$target"
    fi
    
    ln -s "$source" "$target"
    print_success "Đã enable site: $config_name"
}

test_nginx_config() {
    print_info "Kiểm tra cấu hình Nginx..."
    if nginx -t; then
        print_success "Cấu hình Nginx hợp lệ"
        return 0
    else
        print_error "Cấu hình Nginx có lỗi!"
        return 1
    fi
}

reload_nginx() {
    print_info "Reload Nginx..."
    systemctl reload nginx
    print_success "Nginx đã được reload"
}

setup_ssl() {
    local domain=$1
    print_info "Cài đặt SSL certificate cho: $domain"
    
    certbot --nginx -d "$domain" --non-interactive --agree-tos --email "$SSL_EMAIL" --redirect
    
    if [ $? -eq 0 ]; then
        print_success "SSL certificate đã được cài đặt cho: $domain"
    else
        print_warning "Không thể cài SSL cho $domain. Có thể domain chưa trỏ về server."
    fi
}

setup_auto_renew() {
    print_info "Thiết lập tự động gia hạn SSL..."
    
    # Kiểm tra cron job đã tồn tại chưa
    if ! crontab -l 2>/dev/null | grep -q "certbot renew"; then
        (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet --post-hook 'systemctl reload nginx'") | crontab -
        print_success "Đã thiết lập auto-renew SSL (chạy lúc 3:00 AM hàng ngày)"
    else
        print_info "Auto-renew SSL đã được thiết lập trước đó"
    fi
}

create_firewall_rules() {
    print_info "Cấu hình firewall (ufw)..."
    
    if command -v ufw &> /dev/null; then
        ufw allow 'Nginx Full'
        ufw allow OpenSSH
        print_success "Đã mở ports cho Nginx (80, 443)"
    else
        print_warning "UFW không được cài đặt. Bỏ qua cấu hình firewall."
    fi
}

show_summary() {
    echo ""
    echo "============================================================"
    echo -e "${GREEN}HOÀN TẤT CẤU HÌNH DOMAIN${NC}"
    echo "============================================================"
    echo ""
    echo "Các domain đã được cấu hình:"
    echo ""
    echo -e "  ${BLUE}Frontend:${NC}   https://${FRONTEND_DOMAIN}"
    echo -e "  ${BLUE}API:${NC}        https://${API_DOMAIN}"
    echo -e "  ${BLUE}Admin:${NC}      https://${ADMIN_DOMAIN}"
    echo -e "  ${BLUE}phpMyAdmin:${NC} https://${PMA_DOMAIN}"
    echo ""
    echo "============================================================"
    echo "BƯỚC TIẾP THEO:"
    echo "============================================================"
    echo ""
    echo "1. Trỏ các domain về IP của VPS thông qua DNS:"
    echo ""
    echo "   Type: A    Name: ${FRONTEND_DOMAIN%%.*}    Value: YOUR_VPS_IP"
    echo "   Type: A    Name: api         Value: YOUR_VPS_IP"
    echo "   Type: A    Name: admin       Value: YOUR_VPS_IP"
    echo "   Type: A    Name: pma         Value: YOUR_VPS_IP"
    echo ""
    echo "2. Sau khi DNS đã propagate, chạy lại script với option --ssl"
    echo "   để cài đặt SSL certificates."
    echo ""
    echo "3. Đảm bảo Docker containers đang chạy:"
    echo "   docker-compose up -d"
    echo ""
    echo "============================================================"
}

show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --install     Cài đặt config Nginx (không SSL)"
    echo "  --ssl         Cài đặt SSL certificates"
    echo "  --all         Cài đặt config + SSL"
    echo "  --test        Kiểm tra cấu hình Nginx"
    echo "  --help        Hiển thị trợ giúp"
    echo ""
    echo "Ví dụ:"
    echo "  sudo $0 --install    # Cài config trước"
    echo "  sudo $0 --ssl        # Sau khi DNS ok, cài SSL"
    echo ""
}

# ============================================================
# MAIN EXECUTION
# ============================================================

main_install() {
    check_root
    check_nginx
    
    echo ""
    echo "============================================================"
    echo -e "${BLUE}KHODAT VPS DOMAIN CONFIGURATION${NC}"
    echo "============================================================"
    echo ""

    # Backup existing configs
    backup_nginx_config

    # Create Nginx configurations
    create_nginx_config "$FRONTEND_DOMAIN" "$FRONTEND_PORT" "khodat-frontend"
    create_api_nginx_config
    create_nginx_config "$ADMIN_DOMAIN" "$ADMIN_PORT" "khodat-admin"
    create_nginx_config "$PMA_DOMAIN" "$PMA_PORT" "khodat-pma"

    # Enable sites
    enable_site "khodat-frontend"
    enable_site "khodat-api"
    enable_site "khodat-admin"
    enable_site "khodat-pma"

    # Test and reload Nginx
    if test_nginx_config; then
        reload_nginx
    else
        print_error "Có lỗi trong config. Vui lòng kiểm tra lại."
        exit 1
    fi

    # Setup firewall
    create_firewall_rules

    # Show summary
    show_summary
}

main_ssl() {
    check_root
    check_certbot

    echo ""
    print_info "Cài đặt SSL certificates..."
    echo ""

    setup_ssl "$FRONTEND_DOMAIN"
    setup_ssl "$API_DOMAIN"
    setup_ssl "$ADMIN_DOMAIN"
    setup_ssl "$PMA_DOMAIN"

    setup_auto_renew

    print_success "Hoàn tất cài đặt SSL!"
}

# Parse command line arguments
case "${1:-}" in
    --install)
        main_install
        ;;
    --ssl)
        main_ssl
        ;;
    --all)
        main_install
        main_ssl
        ;;
    --test)
        check_root
        test_nginx_config
        ;;
    --help|-h)
        show_help
        ;;
    *)
        echo ""
        print_info "Sử dụng: $0 --help để xem hướng dẫn"
        echo ""
        show_help
        ;;
esac
